### ISSUE TITLE
Powerset

### ISSUE THREAD

**Issue by dotlambda** [ddssff/set-extra#1]
How about adding a function for the [powerset](https://en.wikipedia.org/wiki/Power_set)?

An possible implementation would be:

``` hs
powerset s
  | null s    = singleton empty
  | otherwise = map (Set.insert x) pxs `union` pxs
      where (x,xs) = deleteFindMin s
            pxs = powerset xs
```

(see http://stackoverflow.com/questions/6428279/why-data-set-has-no-powerset-function)

**Comment by ddssff** [comment]
Sure, consider it done!

**Comment by dotlambda** [comment]
Just a question: Isn't it more efficient to check for emptiness with `null` than comparing with the empty set?

**Comment by ddssff** [comment]
It could be, depending on the implementation of foldr in the Foldable instance: https://hackage.haskell.org/package/base-4.8.2.0/docs/src/Data.Foldable.html#null
